export const ROUTER_ROUTES = {
  HOME: "/",
  AUTH: "auth",
  LOGIN: "login",
  PUBLIC: "public",
  REGISTER: "register",
  TERMS_AND_CONDITIONS: "terms-and-conditions",
  PRIVACY_POLICY: "privacy-policy",
  EVENTS_INFO: "events-info",
  CONSULTANCY_INFO: "consultancy-info",
  PRODUCTS_INFO: "products-info",
  RESEND_EMAIL: "resend-email",
  PLASMA: "plasma",
  GATC: "gatc",
  GATC_SPEAKERS: "speakers",
  GATC_PROGRAMS: "programs",
  GATC_PARTICIPANTS: "participants",
  GATC_MY_HANDSHAKES: "my-handshakes",
  MY_BOOKSHELF: "my-bookshelf",
  IMPULSE: "impulse",
};
