export const API_ROUTES = {
  LOGIN: "/login/",
  LOGOUT: "/logout/",
  REGISTER: "/register/",
  USER_PROFILE: "/user-profile/",
  UPDATE_USER_PROFILE: "/user-profile/update-current/",
  REFRESH_TOKEN: "/refresh-token/",
  VERIFY_EMAIL: "/verify-email/",
  RESEND_EMAIL: "/resend-verification/",
  FORGOT_PASSWORD: "/forgot-password/",
  RESET_PASSWORD: "/reset-password/",
  GET_USER_PERSONAL_PROFILE: "/profile/personal/",
  UPDATE_USER_PERSONAL_PROFILE: "/profile/personal/update/",
  GET_USER_PROFESSIONAL_PROFILE: "/profile/professional/",
  UPDATE_USER_PROFESSIONAL_PROFILE: "/profile/professional/update/",
  GET_USER_EDUCATION: "/profile/education/",
  ADD_USER_EDUCATION: "/profile/education/add/",
  UPDATE_USER_EDUCATION: (id: number) => `/profile/education/${id}/update/`,
  DELETE_USER_EDUCATION: (id: number) => `/profile/education/${id}/delete/`,
  // ── GATC Payment ──
  GET_EVENTS: "/events/",
  CREATE_REGISTRATION: "/registrations/",
  CREATE_ORDER: (registrationId: number) => `/create-order/${registrationId}/`,
  VERIFY_PAYMENT: "/verify-payment/",
  MANUAL_PAYMENT: "/manual-payment/",

  // ── Bookshelf ──
  GET_FOLDERS_TREE: "/folders/tree/",
  CREATE_FOLDER: "/folders/",
  CREATE_FOLDER_ITEM: "/folder-items/",
  GATC_PASS: "/public/payment",
  GATC_PROGRAMS: "/programs/",
  GATC_SPEAKERS: "/speakers/",
  GATC_SPEAKER_BY_ID: (id: number | string) => `/speakers/${id}/`,
  GATC_MEMBERS: "/members",

  // ── Handshake ──
  HANDSHAKE_SEND: "/handshake/send/",
  HANDSHAKE_MY: "/handshake/my_handshakes/",
  HANDSHAKE_CANCEL: (id: number) => `/handshake/${id}/cancel/`,
  HANDSHAKE_ACCEPT: (id: number) => `/handshake/${id}/accept/`,
  HANDSHAKE_DECLINE: (id: number) => `/handshake/${id}/decline/`,

  // ── Inbox / Messages ──
  CONVERSATIONS: "/conversations/",
  MESSAGES_SEND: "/messages/",
  MESSAGES_CHAT: (userId: number) => `/messages/chat/${userId}/`,
  MESSAGES_MARK_READ: (userId: number) => `/messages/mark-read/${userId}/`,
  USER_BY_ID: (userId: number) => `/users/${userId}/`,
};
