export const APP_ROUTES = {
  ROOT: "/",
  PLASMA: "/plasma",
  PROFILE: "/user/profile",
  GATC: "/gatc",
  GATC_SPEAKERS: "/gatc/speakers",
  GATC_PROGRAMS: "/gatc/programs",
  GATC_PARTICIPANTS: "/gatc/participants",
  GATC_MEMBER: (id: number | string) => `/gatc/members/${id}`,
  GATC_MY_HANDSHAKES: "/gatc/my-handshakes",
  MY_BOOKSHELF: "/my-bookshelf",
  IMPULSE: "/impulse",
  IMPULSE_FEED: "/impulse/feed",
  AUTH: "/auth",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  RESEND_EMAIL: "/auth/resend-email",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  TERMS_AND_CONDITIONS: "/public/terms-and-conditions",
  PRIVACY_POLICY: "/public/privacy-policy",
  EVENTS_INFO: "/public/events-info",
  CONSULTANCY_INFO: "/public/consultancy-info",
  PRODUCTS_INFO: "/public/products-info",
  GATC_REGISTRATION: "/gatc/registration",
  GATC_VIRTUAL_PASS: "/public/gatc/virtual-pass",
  INBOX: "/inbox",
  MY_ACTIVITY: "/impulse/my-activity",
  USER: "/user/$userId",
  PAGES: "/impulse/pages",
};
