/* 1️⃣ Research Area of Expertise (single) */
export const RESEARCH_AREA_OPTIONS = [
  "Aging and Cancer",
  "Behavioral and Implementation Science",
  "Biochemistry and Biophysics",
  "Bioengineering and Biomaterials",
  "Bioinformatics, Computational Biology, and Systems Biology",
  "Biostatistics",
  "Cancer Disparities Research",
  "Cancer Evolution",
  "Cancer Metabolism",
  "Cancer Modeling",
  "Cancer Prevention Research",
  "Cell Biology",
  "Chemistry and Chemical Biology",
  "Clinical Research",
  "Clinical Trials",
  "Convergence Cancer Science",
  "Data Science and Artificial Intelligence",
  "Developmental Biology",
  "Diagnostics and Biomarkers",
  "Drug Discovery and Development",
  "Early Detection and Interception",
  "Endocrinology",
  "Epigenetics",
  "Experimental and Molecular Therapeutics",
  "Genetics",
  "Genomics",
  "Immunology",
  "Microenvironment",
  "Molecular Biology",
  "Pathology",
  "Pharmacology and Toxicology",
  "Population Sciences",
  "Radiation Science and Medicine",
  "Surgical Oncology",
  "Survivorship Research",
  "Translational Research",
  "Tumor Biology / Tumor Microenvironment",
  "Other",
];

/* 2️⃣ Major Focus */
export const MAJOR_FOCUS_OPTIONS = [
  "Advocacy",
  "Basic Science",
  "Business Development",
  "Clinical Practice",
  "Clinical Research",
  "Population Science",
  "Regulatory Science and Health Policy",
  "Research Administration",
  "Science Education",
  "Science Education and Training",
  "Translational Research",
];

/* 3️⃣ Specific Research Areas (LARGE – searchable) */
export const SPECIFIC_RESEARCH_AREA_OPTIONS = [
  "Aging",
  "AIDS and Cancer",
  "Angiogenesis",
  "Animal Models",
  "Apoptosis",
  "Biochemical Modulators of Therapy and Toxicity",
  "Biological Response Modifiers",
  "Biomarkers",
  "Bone Marrow Transplantation",
  "Cachexia",
  "Cancer Control and Screening",
  "Cancer Disparities",
  "Cancer Epidemiology",
  "Cancer Genetics",
  "Cancer Immunology",
  "Cancer Metabolism",
  "Cancer Stem Cells",
  "Cancer Vaccines",
  "Carcinogenesis",
  "Cell Adhesion Molecules",
  "Cell and Tissue Culture",
  "Cell Cycle Regulation",
  "Cell Death (Apoptosis)",
  "Chemoprevention",
  "Chemotherapy",
  "Chromatin Structure and Function",
  "Clinical Trials",
  "Combined Modalities of Therapy",
  "Computational Biology",
  "DNA Damage and Repair",
  "DNA Methylation",
  "Drug Delivery Systems",
  "Drug Metabolism",
  "Drug Resistance",
  "Early Detection",
  "Epigenetics and Epigenomics",
  "Experimental Immunotherapy",
  "Extracellular Matrix",
  "Flow Cytometry",
  "Gene Expression",
  "Gene Therapy",
  "Genetic Predisposition and Cancer Risk",
  "Imaging",
  "Immunobiology",
  "Immunotherapy (Clinical)",
  "Immunotherapy (Experimental)",
  "Inflammation",
  "Invasion and Metastasis",
  "Microbiome Research",
  "MicroRNAs",
  "Molecular Carcinogenesis",
  "Nanotechnology",
  "Oncogenes",
  "Population-Based Studies",
  "Precision Medicine",
  "Radiation Biology",
  "Radiation Therapy",
  "Signal Transduction",
  "Single-Cell Analysis",
  "Stem Cells",
  "Systems Biology",
  "Tumor Angiogenesis",
  "Tumor Heterogeneity",
  "Tumor Immunology",
  "Tumor Microenvironment",
  "Tumor Progression",
  "Tumor Suppressor Genes",
  "Viral Carcinogenesis",
  "Other",
];

/* 4️⃣ Organ Sites */
export const ORGAN_SITE_OPTIONS = [
  "Bone",
  "Brain and Central Nervous System",
  "Breast",
  "Colon and Rectum",
  "Esophagus",
  "Eye",
  "Gastrointestinal",
  "Head and Neck",
  "Kidney",
  "Larynx",
  "Leukemia",
  "Liver",
  "Lung and Bronchus",
  "Lymphoma",
  "Melanoma",
  "Multiple Myeloma",
  "Neuroblastoma",
  "Ovary",
  "Pancreas",
  "Pediatric",
  "Prostate",
  "Sarcoma and Soft Tissue",
  "Skin",
  "Stomach",
  "Testis",
  "Thyroid",
  "Urinary Bladder",
  "Uterine Cervix",
  "Uterine Corpus",
];

/* 5️⃣ Additional Research Areas */
export const ADDITIONAL_RESEARCH_AREA_OPTIONS = [
  "Aging and Cancer",
  "Behavioral and Implementation Science",
  "Biochemistry and Biophysics",
  "Bioengineering and Biomaterials",
  "Bioinformatics, Computational Biology, and Systems Biology",
  "Biostatistics",
  "Cancer Disparities Research",
  "Cancer Evolution",
  "Cancer Metabolism",
  "Cancer Modeling",
  "Cancer Prevention Research",
  "Cell Biology",
  "Chemistry and Chemical Biology",
  "Clinical Research",
  "Clinical Trials",
  "Convergence Cancer Science",
  "Data Science and Artificial Intelligence",
  "Developmental Biology",
  "Diagnostics and Biomarkers",
  "Drug Discovery and Development",
  "Early Detection and Interception",
  "Endocrinology",
  "Epigenetics",
  "Experimental and Molecular Therapeutics",
  "Genetics",
  "Genomics",
  "Immunology",
  "Microenvironment",
  "Molecular Biology",
  "Pathology",
  "Pharmacology and Toxicology",
  "Population Sciences",
  "Radiation Science and Medicine",
  "Surgical Oncology",
  "Survivorship Research",
  "Translational Research",
  "Tumor Biology / Tumor Microenvironment",
  "Other",
];
